[tool.isort]
line_length = 79

[tool.autopep8]
max_line_length = 79
ignore = ["E731", "W391"]

[tool.pylint."messages control"]
disable = ["redefined-outer-name", "invalid-name", "no-member",
           "unused-wildcard-import", "unsubscriptable-object", "wildcard-import",
           "wrong-import-position", "cell-var-from-loop", "unused-argument"]

[tool.pylint.miscellaneous]
notes = ["XXX", "TODO"]

[tool.pylint.format]
max-line-length = 200
max-module-lines = 4000

[tool.pylint.design]
max-args = 10
max-locals = 35
max-statements = 100
max-attributes = 30
min-public-methods = 1
